django_prject1/app1/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import index, visualiser,Graphe,stats,file_loi_view,test_traitement

urlpatterns = [
            path('', index, name='index'),
            path('visualiser/',visualiser, name='visualiser'),
            path('Graphe/',Graphe, name='Graphe'),
            path('statistiques/',stats, name='statistiques'),
            path('loi/', file_loi_view , name='loi'),
            path('test_traitement',test_traitement,name='test_traitement')
            
]

django_prject1/django_prject1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app1.urls")),    
]

django_prject1/app1/models.py
from django.db import models

# Create your models here.
from django.db import models

django_prject1/app1/forms.py
# forms.py
from django import forms
class FileUploadForm(forms.Form):
    file = forms.FileField(label='Sélectionnez un fichier')

class ChooseColumnsForm(forms.Form):
    col_name1 = forms.ChoiceField( choices=(), required=True)
    col_name2 = forms.ChoiceField( choices=(), required=True)

    def __init__(self, *args, **kwargs):
        column_choices = kwargs.pop('column_choices', None)

        super(ChooseColumnsForm, self).__init__(*args, **kwargs)

        if column_choices:
            self.fields['col_name1'].choices = column_choices
            self.fields['col_name2'].choices = column_choices


   

django_prject1/app1/views.py
import io
import os
from urllib import request
from flask import redirect
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')  # Utilisez le backend 'Agg' (non interactif) au lieu du backend par défaut
import matplotlib.pyplot as plt
import matplotlib
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from scipy.stats import bernoulli ,binom ,expon, norm, poisson,uniform
from io import BytesIO, StringIO
import base64
import seaborn as sns
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from .forms import FileUploadForm,ChooseColumnsForm



#  Create your views here.
def index(request): 
        return render(request, 'app1/index.html')
       
def visualiser(request):

    if request.method == 'POST':
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            fichier = request.FILES['file']
            #  Traitement pour les fichiers Excel
            if fichier.name.endswith(('.xls', '.xlsx')):
                try:
                    data = pd.read_excel(fichier)
                    df = pd.DataFrame(data)
                    return render(request, 'app1/visualiser.html', {'df': df.to_html(classes='table table-bordered')})
                except pd.errors.ParserError:
                    return HttpResponse("Erreur lors de la lecture du fichier Excel. Veuillez vérifier le format du fichier.")

            #  Traitement pour les fichiers CSV
            elif fichier.name.endswith('.csv'):
                try:
                    data = pd.read_csv(fichier)
                    df = pd.DataFrame(data)
                    return render(request, 'app1/visualiser.html', {'df': df.to_html(classes='table table-bordered')})
                except pd.errors.ParserError:
                    return HttpResponse("Erreur lors de la lecture du fichier CSV. Veuillez vérifier le format du fichier.")

            else:
                #  Fichier non pris en charge
                return HttpResponse("Seuls les fichiers Excel (.xls, .xlsx) ou CSV (.csv) sont autorisés. Veuillez télécharger un fichier valide.")
    else:
        form = FileUploadForm()
    
    return render(request, 'app1/visualiser.html', {'form': form})


def Graphe(request):  
    file_name = None  # Initialize with a default value
    plot_url = None 
    plot = None 
    df_head = pd.DataFrame()
    df=None
    if request.method == 'POST':
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
           
            file_name = request.FILES['file'].name  
            selected_graph = request.POST.get('graph')
            val1 = request.POST.get('val1')
            val2 = request.POST.get('val2')
            
            plt.figure()

            file_extension = os.path.splitext(file_name)[1]

            uploaded_file = form.cleaned_data['file']
            if  file_extension == '.csv':
                
                df = pd.read_csv(uploaded_file)
                df_head = df.head()
                sns.set(style="whitegrid")
                if selected_graph == '1' : 
                          with sns.axes_style("darkgrid"):
                           # Define a color palette for better distinction
                            palette = sns.color_palette("husl", 3)  # You can adjust the number of colors
                            
                            # Create a line plot with enhanced styling
                            plot = sns.lineplot(x=val1, y=val2, data=df, marker='o', color=palette[0], linestyle='-', linewidth=2, label='Line Plot')

                            plot.set_xlabel=val1
                            plot.set_ylabel=val2
                            # Customize the grid
                            plot.grid(axis='both', linestyle='--', alpha=0.7)
                            # Customize tick parameters
                            plot.tick_params(axis='both', which='major', labelsize=10)

                if selected_graph == '2' : 
                          plot = sns.scatterplot(x=val1, y=val2,data=df, marker='o', s=50,color='red')                          
                          plot.set_xlabel=val1
                          plot.set_ylabel=val2

                          
                if selected_graph == '3' :
                          palette = sns.color_palette("Paired")  
                          plot= sns.boxplot(x=val1,y=val2,data=df, palette=palette, width=0.5)
                          plot.set_xlabel=val1
                          plot.set_ylabel=val2
                          plot.set_title('Box Plot', fontsize=14)
                           # Customize the grid
                          plot.grid(axis='y', linestyle='--', alpha=0.7)

                            # Customize tick parameters
                          plot.tick_params(axis='both', which='major', labelsize=10)
                          plt.tight_layout()

                if selected_graph == '4' : 
                          plot= sns.histplot(x=val1,data=df)  
                          plot.set_xlabel=val1

                if selected_graph == '5' : 
                          plot= sns.kdeplot(x=val1,data=df)     
                          plot.set_xlabel=val1 

                if selected_graph == '6' : 
                          plot= sns.violinplot(x=val1,data=df)   
                          plot.set_xlabel=val1  

                if selected_graph == '7' : 
                          plot= sns.barplot(x=val1,y=val2,data=df)  
                          plot.set_xlabel=val1
                          plot.set_ylabel=val2

                if selected_graph == '8' : 
                          dff = df.select_dtypes(include=['number'])
                          correlation_matrix = dff.corr()
                          plot=sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm")
                          plt.title('Heatmap')

                if selected_graph == '9' : 
                          category_counts = df[val1].value_counts()
                          plot=plt.pie(category_counts, labels=category_counts.index, autopct='%1.1f%%', startangle=140)

               # Save the plot as an image  
               
               # Save the plot as an image (you can save it to a file or encode it as base64)
                buffer = io.BytesIO()
                plt.savefig(buffer, format='png')
                buffer.seek(0)
                image_png = buffer.getvalue()
                buffer.close()
                # Close all     Matplotlib figures to clear the state
                plt.close()
                # Encode the plot to base64
                plot_url = base64.b64encode(image_png).decode('utf-8')


            if  file_extension in ('.xlsx', '.xls'): 
                
                uploaded_file = form.cleaned_data['file']
                df = pd.read_excel(uploaded_file)
                # Process the DataFrame
                sns.set(style="whitegrid")
                plot = sns.relplot(data=df)
                # Save the plot as an image (you can save it to a file or encode it as base64)
                buffer = io.BytesIO()
                plot.savefig(buffer, format='png')
                buffer.seek(0)
                image_png = buffer.getvalue()
                buffer.close()
                 # Get the first five rows of the DataFrame
                print(df_head)
                # Encode the plot to base64
                plot_url = base64.b64encode(image_png).decode('utf-8')

    else:
        form = FileUploadForm()
    return render(request, 'app1/Graphe.html', {'form': form, 'file_name': file_name, 'plot_url': plot_url, 'df_head': df_head})

def file_loi_view(request):
                 
                selected_graph = request.POST.get('graph')
                val1 = request.POST.get('val1')
                val2 =request.POST.get('val2')
                            
           
                if selected_graph == '1' :
                          data_bern = bernoulli.rvs(size=1000,p= float (val1))
                          plot = sns.histplot(data_bern, kde=True, stat='probability')
                          plot.set(xlabel='Bernoulli', ylabel='Probabilité')

                if selected_graph == '2' :
                         
                          data_binom = binom.rvs(n=int (val2),p=float (val1),loc=0,size=1000)
                          plot = sns.histplot(data_binom, kde=True, stat='probability')
                          plot.set(xlabel='Binomial', ylabel='Probabilité')

                if selected_graph == '3' :
                          
                          data_unif = uniform.rvs(loc=int (val1), scale=int (val2), size=1000)
                          plt.figure(figsize=(6,4))
                          plot = sns.histplot(data_unif, kde=True, stat='probability')
                          
                if selected_graph == '4' :
                          data_binom = poisson.rvs(mu=int (val1), size=10000)
                          plot = sns.histplot(data_binom, kde=True, stat='probability')
                          plot.set(xlabel='Poisson', ylabel='Probabilité')
                if selected_graph == '5' :
                          data = norm.rvs(loc=int (val1), scale=int (val2), size=1000)
                          plot = sns.kdeplot(data, fill=True)

                if selected_graph == '6' :
                          data = expon.rvs(scale=float (val1), size=1000)
                          plot=sns.kdeplot(data, fill=True)

               # Save the plot as an image  
               
               # Save the plot as an image (you can save it to a file or encode it as base64)
                buffer = io.BytesIO()
                plt.savefig(buffer, format='png')
                buffer.seek(0)
                image_png = buffer.getvalue()
                buffer.close()

django_prject1/app1/templates/app1/Graphe.html
<!DOCTYPE html>
<html>

<head>
    <title>Graph</title>
    <!-- Add this in the <head> section -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+WyldQST4vX3jPaRTWR83pM4p4MEelQ" crossorigin="anonymous">

    <!-- Optional: Add Bootstrap JavaScript (Popper.js and Bootstrap JS) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
        integrity="sha384-9aYxh5A5JDQO5bwnM0v8F2VvzPqUAb5T9CkssMmPkO6d5i7e6UxjR6q5WxUpGW+1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8sh+WyldQST4vX3jPaRTWR83pM4p4MEelQ"
        crossorigin="anonymous"></script>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f7e9e9;
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        form {
            max-width: 600px;
            margin: 20px auto;
            background-color: #fc9ec7;
            padding: 20px;
            border: 1px solid #fc9ec7;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 1);
        }

        fieldset {
            border: 1px solid #dddddd;
            padding: 10px;
            margin-bottom: 15px;
            border-radius: 5px;
        }

        legend {
            font-size: 1.2em;
            font-weight: bold;
        }

        .form-check {
            margin-bottom: 10px;
            padding: 10px;
        }



        .form-check input {
            margin-right: 5px;
        }

        .form-group {
            margin-bottom: 15px;
        }

        input[type="text"] {
            width: 100%;
            padding: 8px;
            box-sizing: border-box;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        .btn {
            display: inline-block;
            padding: 8px 12px;
            font-size: 16px;
            text-align: center;
            text-decoration: none;
            cursor: pointer;
            border: 1px solid #EA5395;
            border-radius: 4px;
            color: #fff;
            background-color: #EA5395;
        }

        .btn:hover {
            background-color: #EA5395;
            border-color: #EA5395;
        }

        .upload-section {
            text-align: center;
            margin-bottom: 20px;
        }

        .upload-section h2 {
            color: #EA5395;
            margin-bottom: 10px;
        }

        .upload-section p {
            color: #555;
            font-size: 14px;
        }

        /* Styles for the uploaded file visualization */
        .uploaded-visualization {
            text-align: center;
            margin-top: 20px;
        }

        .uploaded-visualization img {
            max-width: 100%;
            height: auto;
            border: 1px solid #ddd;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 1);
        }

        .thead-dark th {
            background-color: #343a40;
            color: #fff;
        }
        .navbar {
            padding: 25px;

        }
        
    </style>
</head>

<body class="container mt-4">
    <div class="navbar"></div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <h1></h1>
        <fieldset>
            <div>
                <input type="checkbox" class="showInputCheckbox" name="graph" value="1" id="linePlot">
                <label class="form-check-label" for="linePlot">Line Plot</label>
            </div>

            <div>
                <input type="checkbox" class="showInputCheckbox" name="graph" value="2" id="scatterPlot">
                <label class="form-check-label" for="scatterPlot">Scatter Plot</label>
            </div>

            <div>
                <input type="checkbox" class="showInputCheckbox" name="graph" value="3" id="boxPlot">
                <label class="form-check-label" for="boxPlot">Box Plot</label>
            </div>

            <div>
                <input type="checkbox" class="showInputCheckbox" name="graph" value="4" id="histogramPlot">
                <label class="form-check-label" for="histogramPlot">Histogram Plot</label>
            </div>
            </div>

            <div>
                <input type="checkbox" class="showInputCheckbox" name="graph" value="5" id="kdePlot">
                <label class="form-check-label" for="kdePlot">KDE Plot</label>
            </div>
            </div>

            <div>
                <input type="checkbox" class="showInputCheckbox" name="graph" value="6" id="violinPlot">
                <label class="form-check-label" for="violinPlot">Violin Plot</label>
            </div>
            </div>
            <div>
                <input type="checkbox" class="showInputCheckbox" name="graph" value="7" id="barPlot">
                <label class="form-check-label" for="barPlot">Bar Plot</label>
            </div>
            <div>
                <input type="checkbox" class="showInputCheckbox" name="graph" value="8" id="heatmap">
                <label class="form-check-label" for="heatmap">Heatmap</label>
            </div>
            <div>
                <input type="checkbox" class="showInputCheckbox" name="graph" value="9" id="piechart">
                <label class="form-check-label" for="piechart">Pie Chart</label>
            </div>
            <br>

            <div class="form-group">
                <input type="text" class="form-control hiddenInput" name="val1" placeholder="Valeur1">
            </div>
            <div class="form-group">
                <input type="text" class="form-control hiddenInput" name="val2" placeholder="Valeur2"><br>
            </div>
        </fieldset>
        <button type="submit" class="btn btn-primary btn-block" value="Upload">Upload</button>
    </form>

    {% if plot_url %}
    <div class="uploaded-visualization">
        <h2 class="text-center mt-4">Graph</h2>
        <img src="data:image/png;base64,{{ plot_url}}" alt="Seaborn Plot" class="img-fluid">
    </div>
    {% endif %}

    <script>
        // Get the checkbox and input elements by their IDs
        const showInputCheckboxes = document.getElementsByClassName('showInputCheckbox');
        const hiddenInputs = document.getElementsByClassName('hiddenInput');

        for (let i = 0; i < showInputCheckboxes.length; i++) {
            // Add an event listener to each checkbox to toggle the input visibility
            showInputCheckboxes[i].addEventListener('change', function () {
                // Loop through all elements with the class name 'hiddenInput'
                for (let j = 0; j < hiddenInputs.length; j++) {
                    hiddenInputs[j].style.display = this.checked ? 'block' : 'none';
                }
            });
        }

    </script>

</body>

</html>

django_prject1/app1/templates/app1/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>django Project</title>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    {% block styles %}
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
        <link href="{% static 'plugins/elegant_font/css/style.css' %}" rel="stylesheet">
        <link href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'fontawesome/js/all.js' %}" rel="stylesheet">
    {% endblock %}
</head>
<body class="landing-page">
    
    <div class="page-wrapper">
        <!-- ******Header****** -->
        <header class="header text-center">
            <div class="container">
                <div class="branding">
                    <h1 class="logo">
                        <img  src="{% static 'plugins/elegant_font/images/PNG/statistiques1.png' %}" alt="logo"
                            /> <h3 style="margin-left: 10px;">Data Visualization</h3>
                        
                    </h1>
                </div><!--//branding-->      
        </header><!--//header-->

        <section class="cards-section text-center">
                <div id="cards-wrapper" class="cards-wrapper row">

                    <div class="item item-green col-lg-4 col-6">
                        <div class="item-inner">
                            <div class="icon-holder">
                                <span aria-hidden="true" class="icon icon_genius"></span>
                                <i class="icon fa fa-paper-plane"></i>
                            </div><!--//icon-holder-->
                            <h3 class="title">visualiser le fichier</h3>         
                            <p class="intro">Présentez vos données sous forme de tableau</p>
                            <a class="link" href="{% url 'visualiser' %}"></a>
                        </div><!--//item-inner-->
                    </div><!--//item-->
                
                    <div class="item item-pink item-2 col-lg-4 col-6">
                        <div class="item-inner">
                            <div class="icon-holder">
                                <span aria-hidden="true" class="icon icon_puzzle_alt"></span>
                            </div><!--//icon-holder-->
                            <h3 class="title">Graphe</h3>
                            <p class="intro">Outil de conception de diagrammes</p>
                            <a class="link" href="{% url 'Graphe' %}"><span></span></a>
                        </div><!--//item-inner-->
                    </div><!--//item-->
                    
                    <div class="item item-blue col-lg-4 col-6">
                        <div class="item-inner">
                            <div class="icon-holder">
                                <span aria-hidden="true" class="icon icon_datareport_alt"></span>
                            </div><!--//icon-holder-->
                            <h3 class="title">Parcoure des donnes</h3>
                            <p class="intro">Lorem ipsum dolor sit amet, consectetuer adipiscing elit</p>
                            <a class="link" href="{% url 'statistiques' %}"><span></span></a>
                        </div><!--//item-inner-->
                    </div><!--//item-->

                    <div class="item item-purple col-lg-4 col-6">
                        <div class="item-inner">
                            <div class="icon-holder">
                                <span aria-hidden="true" class="icon icon_lifesaver"></span>
                            </div><!--//icon-holder-->
                            <h3 class="title">Loi</h3>
                            <p class="intro">Layout for FAQ page. Lorem ipsum dolor sit amet, consectetuer adipiscing elit</p>
                            <a class="link" href="{% url 'loi' %}"><span></span></a>
                        </div><!--//item-inner-->
                    </div><!--//item-->

                    <div class="item item-pink item-2 col-lg-4 col-6">
                        <div class="item-inner">
                            <div class="icon-holder">
                                <span aria-hidden="true" class="icon icon_puzzle_alt"></span>
                            </div><!--//icon-holder-->
                            <h3 class="title">Graphe</h3>
                            <p class="intro">Outil de conception de diagrammes</p>
                            <a class="link" href="{% url 'test' %}"><span></span></a>
                        </div><!--//item-inner-->
                    </div><!--//item-->
                    
                </div><!--//cards-->  
            </div><!--//container-->
        
        </section><!--//cards-section-->
    </div><!--//page-wrapper-->

    <footer class="footer text-center">
        <div class="container">
            
            
        </div><!--//container-->
    </footer><!--//footer-->

    <!-- Main Javascript -->
    <script src="static/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script src="static/plugins/stickyfill/dist/stickyfill.min.js"></script>
    <script src="{% static '/js/main.js' %}"></script>
    

</body>
</html>
    

django_prject1/app1/templates/app1/visualiser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Visualiser</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #cefcd5;
            /* Ajoutez la couleur de fond souhaitée */
        }

        .card {
            background-color: #fff;
            border-radius: 8px;
            /* Ajustez la valeur pour correspondre à la bordure du tableau */
            box-shadow: 0 0 10px rgba(0, 0, 0, 1);
            margin-top: 40px;
            /* Espace entre la navbar et la carte */
            padding: 20px;
            width: 80%;
            /* Ajustez la largeur selon vos besoins */
            margin: auto;
            /* Centre horizontalement */
        }

        .navbar {
            padding: 20px;

        }

        .docs-search-form input[type="file"],
        .docs-search-form button {
            background-color: #527853;
            color: #ffffff;
            border: 1px solid #ffffff;
            /* border-radius: 4px;
            padding: 8px 12px; */
            cursor: pointer;
            margin-right: 5px;
            /* Ajout d'un espace de 5px entre les deux éléments */
            margin-top: 5px;
        }

        .table.table-bordered {
            width: 100%;
            margin-bottom: 1rem;
            color: #212529;
            border-collapse: collapse;
        }

        .table.table-bordered th,
        .table.table-bordered td {
            padding: 0.75rem;
            vertical-align: top;
            border-top: 1px solid #dee2e6;
        }

        .table.table-bordered thead th {
            background-color: #527853;
            color: #fff;
            border-color: #527853;
        }

        .table.table-bordered tbody tr:nth-of-type(odd) {
            background-color: rgba(0, 123, 255, 0.05);
        }

        .table.table-bordered tbody tr:hover {
            background-color: rgba(0, 123, 255, 0.1);
        }
    </style>
</head>

<body>
    <div class="navbar">
        <div class="d-grid gap-2">
            <form method="post" enctype="multipart/form-data" class="docs-search-form row gx-1 align-items-center"
                action="{% url 'visualiser' %}" id="fileUploadForm">
                {% csrf_token %}
                <input type="file" name="file" id="id_file" accept=".xls, .xlsx, .csv">
                <button class="btn btn-primary" type="submit">Importer le fichier</button>
            </form>
        </div>
    </div>


    <div>
        <div class="card">
            <table class="table table-bordered">{{ df|safe }}</table>
        </div>
    </div>

</body>

</html>